apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts  # Repo oficial de Helm
    chart: kube-prometheus-stack
    targetRevision: 69.8.0
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/evilsysadmin/aws-eks-dummycorp/setup/apps/kube-prometheus-stack/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  
