apiVersion: v2
name: kube-prometheus-stack
description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards, and Prometheus rules combined with documentation and scripts to provide easy to operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus Operator.
type: application
home: https://github.com/prometheus-community/helm-charts
sources:
  - https://github.com/prometheus-operator/kube-prometheus
  - https://github.com/prometheus-operator/prometheus-operator
  - https://github.com/prometheus/prometheus
  - https://github.com/prometheus/alertmanager
  - https://github.com/prometheus/node_exporter
  - https://github.com/kubernetes/kube-state-metrics
  - https://github.com/grafana/grafana
version: 69.8.0
appVersion: v0.69.1
dependencies:
  - name: kube-state-metrics
    version: "5.14.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kubeStateMetrics.enabled
  - name: prometheus-node-exporter
    version: "4.23.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: nodeExporter.enabled
  - name: grafana
    version: "7.0.*"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled