apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: aws-acm-issuer
spec:
  acme:
    email: info@evilsysadmin.click
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acm-private-key
    solvers:
      - dns01:
          route53:
            region: eu-wast-1
            domain: "evilsysadmin.click"  # Descubre automáticamente la Hosted Zone
