applications:
  - name: core-infra-apps
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/evilsysadmin/aws-eks-dummycorp.git
      targetRevision: setup
      path: apps/
      directory:
        recurse: true
        include: "*.yaml"
    destination:
      server: https://kubernetes.default.svc
      namespace: core-infra-apps
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  - name: dummycorp-store
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/evilsysadmin/dummycorp-store-code.git
      targetRevision: DUMMYCORP-3
      path: manifests/
      directory:
        recurse: true
        include: "*.yaml"
    destination:
      server: https://kubernetes.default.svc
      namespace: dummycorp-store
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
