apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.15.0
    helm:
      values: |
        provider: aws
        domainFilters:
          - evilsysadmin.click
        logLevel: debug
        policy: sync
        registry: txt
        sources: 
          - ingress
        txtOwnerId: "k8s"
        serviceAccount:
          create: true
          name: external-dns
          annotations:
            eks.amazonaws.com/role-arn: 'arn:aws:iam::980921756231:role/external_dns_irsa_role'

  destination:
    server: https://kubernetes.default.svc
    namespace: core-infra-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true