# apps/clusterissuer/clusterissuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "info@evilsysadmin.click"
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - dns01:
        route53:
          region: "eu-west-1"
          hostedZoneID: ""  # Placeholder, será reemplazado por Kustomize